[build]
  base = "frontend/vue-anlix"
  publish = "dist"
  command = "npm install && npm run build"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200